# Generated by Django 5.0.7 on 2024-07-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("complete", models.BooleanField(default=False)),
                ("at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
